# Generated by Django 5.2.6 on 2025-11-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('hostel_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=1)),
                ('occupied', models.IntegerField(default=0)),
                ('room_type', models.CharField(default='General', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_rating', models.IntegerField(default=0)),
                ('quality_rating', models.IntegerField(default=0)),
                ('quantity_rating', models.IntegerField(default=0)),
                ('hygiene_rating', models.IntegerField(default=0)),
                ('overall_rating', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_feedback', to='hostelapi.student')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('plumbing', 'Plumbing'), ('wifi', 'Wi-Fi'), ('food', 'Food'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapi.student')),
            ],
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_date', models.DateField(auto_now_add=True)),
                ('vacate_date', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapi.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapi.student')),
            ],
        ),
    ]
